# Ansible/roles/user_management/tasks/main.yml
---
- name: Login to Docker Hub
  community.docker.docker_login:
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_password }}"
    reauthorize: yes

- name: Build Docker image for user_management
  community.docker.docker_image:
    build:
      path: /var/lib/jenkins/workspace/sprinboot_sample_deployment/user_management
    name: "{{ dockerhub_username }}/user_management"
    tag: latest
    source: build

- name: Push Docker image for user_management
  community.docker.docker_image:
    name: "{{ dockerhub_username }}/user_management:latest"
    push: yes
