---
- name: Authenticate to AWS ECR
  shell: |
    aws ecr get-login-password --region {{ AWS_REGION }} | docker login --username AWS --password-stdin {{ AWS_ID }}.dkr.ecr.{{ AWS_REGION }}.amazonaws.com
  register: ecr_login
  changed_when: "'Login Succeeded' in ecr_login.stdout"

- name: Build Docker image for user_management
  shell: |
    docker build -t {{ AWS_ID }}.dkr.ecr.{{ AWS_REGION }}.amazonaws.com/user_management:latest .
  args:
    chdir: /var/lib/jenkins/workspace/springboot_sample_deployment/user_management

- name: Push Docker image for user_management to AWS ECR
  shell: |
    docker push {{ AWS_ID }}.dkr.ecr.{{ AWS_REGION }}.amazonaws.com/user_management:latest
