---
- name: Authenticate to AWS ECR
  shell: |
    echo "{{ AWS_ECR_PASSWORD }}" | docker login --username "{{ AWS_ECR_USERNAME }}" --password-stdin {{ AWS_ID }}.dkr.ecr.{{ AWS_REGION }}.amazonaws.com

- name: Build Docker image for order_management
  shell: |
    docker build -t {{ AWS_ID }}.dkr.ecr.{{ AWS_REGION }}.amazonaws.com/order_management:latest /var/lib/jenkins/workspace/springboot_sample_deployment/order_management

- name: Push Docker image for order_management to AWS ECR
  shell: |
    docker push {{ AWS_ID }}.dkr.ecr.{{ AWS_REGION }}.amazonaws.com/order_management:latest
