# Ansible/roles/order_management/tasks/main.yml
---

- name: Login to Docker Hub
  community.docker.docker_login:
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_password }}"
    reauthorize: yes

- name: Build Docker image for order_management
  community.docker.docker_image:
    build:
      path: /var/lib/jenkins/workspace/springboot_sample_deployment/order_management
    name: "{{ dockerhub_username }}/order_management"
    tag: latest
    source: build

- name: Push Docker image for order_management
  community.docker.docker_image:
    name: "{{ dockerhub_username }}/order_management:latest"
    push: yes
    source: local
