# roles/order_service_setup/tasks/main.yml
---
# Task 1: Ensure Orders Service directory exists
- name: Ensure Orders Service directory exists
  file:
    path: "{{ orders_project_dir }}"
    state: directory
    mode: '0755'

# Task 2: Build Order Management JAR using Maven
- name: Build Order Management JAR using Maven
  command: mvn clean package -DskipTests
  args:
    chdir: "{{ orders_project_dir }}"
  register: order_maven_result
  changed_when: "'BUILD SUCCESS' in order_maven_result.stdout"
  ignore_errors: no

# Task 3: Copy Dockerfile to Remote Server
- name: Copy Dockerfile to remote machine
  copy:
    src: "Dockerfile"
    dest: "{{ orders_project_dir }}/Dockerfile"
    mode: '0644'

# Task 4: Copy JAR file to Docker build context
- name: Copy Orders Service JAR file
  copy:
    src: "{{ orders_project_dir }}/target/{{ orders_jar_file }}"
    dest: "{{ orders_project_dir }}/app.jar"
    mode: '0755'

# Task 5: Remove Existing Orders Service Container (if exists)
- name: Remove existing Orders Service container (if exists)
  docker_container:
    name: orders-service
    state: absent
  ignore_errors: yes

# Task 6: Build Orders Service Docker Image
- name: Build Orders Service Docker Image
  docker_image:
    name: springboot-orders-service
    build:
      path: "{{ orders_project_dir }}"
      dockerfile: "{{ orders_project_dir }}/Dockerfile"
    source: build

# Task 7: Run Orders Service Container
- name: Start Orders Service Container
  docker_container:
    name: orders-service
    image: springboot-orders-service
    state: started
    restart_policy: always
    links:
      - postgres-container
    ports:
      - "8082:8082"
    env:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-container:5432/docker_trials"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "funkY!123"
