apiVersion: v1
kind: Secret
metadata:
  name: aws-ecr-secret
  namespace: default
data:
  .dockerconfigjson: "{{ lookup('pipe', 'aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 145023095187.dkr.ecr.eu-north-1.amazonaws.com && cat ~/.docker/config.json | base64 -w 0') }}"
type: kubernetes.io/dockerconfigjson
