apiVersion: v1
kind: Secret
metadata:
  name: aws-ecr-secret
  namespace: default
data:
  .dockerconfigjson: {{ lookup('pipe', 'aws ecr get-login-password --region eu-north-1 | base64 -w 0') }}
type: kubernetes.io/dockerconfigjson
