apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-management
  template:
    metadata:
      labels:
        app: order-management
    spec:
      containers:
        - name: order-management
          image: sagarkrishnasuresh/order_management:latest
          ports:
            - containerPort: 8082
          envFrom:
            - secretRef:
                name: postgres-credentials
