apiVersion: v1
kind: Service
metadata:
  name: order-management-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: order-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: LoadBalancer
