apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Use "nlb" for Network Load Balancer or "elb" for Classic Load Balancer
spec:
  selector:
    app: user-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
