apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
        - name: user-management
          image: "{{AWS_ACCOUNT_ID}}.dkr.ecr.{{AWS_REGION}}.amazonaws.com/user_management:latest"
          ports:
            - containerPort: 8080
          env:
            - name: AWS_ID
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: AWS_ID
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: AWS_REGION
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD
      imagePullSecrets:
        - name: aws-ecr-secret
