---
- name: Deploy Spring Boot and PostgreSQL Containers (Without Docker Compose)
  hosts: localhost
  become: yes  # Run as sudo/root
  become_method: sudo
  become_user: root
  become_flags: "-n"

  vars:
    project_dir: ~/dockertrials
    orders_project_dir: /home/sagarkrishna/Desktop/orderservice
    jar_file: dockertrials-0.0.1-SNAPSHOT.jar
    orders_jar_file: order-service-0.0.1-SNAPSHOT.jar

  roles:
    - environment_setup
    - database_container_setup
    - springboot_app
    - nginx_setup
    - order_service_setup
