# roles/device_setup/tasks/main.yml
---
- name: Install required packages
  apt:
    name:
      - docker.io
      - ansible
      - python3-pip
    state: present
    update_cache: yes

- name: Install Docker SDK for Python
  pip:
    name: docker

- name: Enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
