# Ansible/roles/device_setup/tasks/main.yml
---
- name: Install Docker and dependencies
  apt:
    name:
      - docker.io
      - ansible
      - python3-pip
    state: present
    update_cache: yes

- name: Install Docker SDK for Python
  pip:
    name: docker

- name: Enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

# ✅ Install kubectl
- name: Download kubectl binary
  get_url:
    url: https://dl.k8s.io/release/v1.27.0/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'
    args:
      creates: /usr/local/bin/kubectl



- name: Verify kubectl installation
  command: kubectl version --client
  register: kubectl_result
  ignore_errors: yes

- name: Display kubectl version
  debug:
    msg: "{{ kubectl_result.stdout }}"

# ✅ Ensure kubectl is available in Jenkins PATH
- name: Create symbolic link for kubectl
  file:
    src: /usr/local/bin/kubectl
    dest: /usr/bin/kubectl
    state: link
    force: yes

- name: Ensure kubectl is accessible by Jenkins user
  lineinfile:
    path: /home/jenkins/.bashrc
    line: 'export PATH=$PATH:/usr/local/bin'
    create: yes
    mode: '0644'

- name: Apply .bashrc changes for Jenkins user
  command: bash -c "source /home/jenkins/.bashrc"
  become_user: jenkins

