---
- name: Install Required Packages
  yum:
    name:
      - docker
      - ansible
      - python3-pip
      - jq
    state: present
    update_cache: yes

- name: Install AWS CLI
  shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
  args:
    creates: /usr/local/bin/aws

- name: Install Docker SDK for Python
  pip:
    name: docker

- name: Enable and Start Docker Service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Install kubectl for EKS
  get_url:
    url: https://dl.k8s.io/release/v1.27.0/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Verify kubectl Installation
  command: kubectl version --client
  register: kubectl_result
  ignore_errors: yes

- name: Install eksctl (for managing AWS EKS)
  get_url:
    url: "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz"
    dest: "/tmp/eksctl.tar.gz"

- name: Extract and Move eksctl
  shell: |
    tar -xzf /tmp/eksctl.tar.gz -C /usr/local/bin
    chmod +x /usr/local/bin/eksctl
  args:
    creates: /usr/local/bin/eksctl
