# Ansible/roles/postgres_setup/tasks/main.yml
---
- name: Generate Kubernetes Secrets for PostgreSQL
  template:
    src: kubernetes-secrets.yml.j2
    dest: /tmp/kubernetes-secrets.yml

- name: Apply PostgreSQL Secrets in Kubernetes
  command: kubectl apply -f /tmp/kubernetes-secrets.yml
  environment:
    KUBECONFIG: "/var/lib/jenkins/.kube/config"
    MINIKUBE_HOME: "/var/lib/jenkins/.minikube"
    PATH: "/usr/local/bin:/usr/bin:/bin"

- name: Deploy PostgreSQL in Kubernetes
  command: kubectl apply -f /var/lib/jenkins/workspace/springboot_sample_deployment/kubernetes/postgres-deployment.yml
  environment:
    KUBECONFIG: "/var/lib/jenkins/.kube/config"
    MINIKUBE_HOME: "/var/lib/jenkins/.minikube"
    PATH: "/usr/local/bin:/usr/bin:/bin"

- name: Deploy PostgreSQL Service in Kubernetes
  command: kubectl apply -f /var/lib/jenkins/workspace/springboot_sample_deployment/kubernetes/postgres-service.yml
  environment:
    KUBECONFIG: "/var/lib/jenkins/.kube/config"
    MINIKUBE_HOME: "/var/lib/jenkins/.minikube"
    PATH: "/usr/local/bin:/usr/bin:/bin"
