# Ansible/roles/postgres_setup/tasks/main.yml
---
- name: Generate Kubernetes Secrets for PostgreSQL
  template:
    src: kubernetes-secrets.yml.j2
    dest: /tmp/kubernetes-secrets.yml

- name: Apply PostgreSQL Secrets in Kubernetes
  command: kubectl apply -f /tmp/kubernetes-secrets.yml

- name: Deploy PostgreSQL in Kubernetes
  command: kubectl apply -f ../../kubernetes/postgres-deployment.yml

- name: Deploy PostgreSQL Service in Kubernetes
  command: kubectl apply -f ../../kubernetes/postgres-service.yml
