---
- name: Authenticate to AWS ECR
  shell: |
    aws ecr get-login-password --region {{ AWS_REGION }} | docker login --username AWS --password-stdin {{ AWS_ID }}.dkr.ecr.{{ AWS_REGION }}.amazonaws.com
  environment:
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
  register: ecr_login
  changed_when: "'Login Succeeded' in ecr_login.stdout"


- name: Generate Kubernetes Secrets for PostgreSQL
  template:
    src: kubernetes-secrets.yml.j2
    dest: /tmp/kubernetes-secrets.yml

- name: Apply PostgreSQL Secrets in AWS EKS
  command: kubectl apply -f /tmp/kubernetes-secrets.yml
  environment:
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    KUBECONFIG: "/home/ec2-user/.kube/config"
    PATH: "/usr/local/bin:/usr/bin:/bin"

- name: Pull Official PostgreSQL Image
  shell: |
    docker pull postgres:latest

- name: Tag PostgreSQL Image for AWS ECR
  shell: |
    docker tag postgres:latest {{ AWS_ID }}.dkr.ecr.{{ AWS_REGION }}.amazonaws.com/postgres:latest

- name: Push PostgreSQL Image to AWS ECR
  shell: |
    docker push {{ AWS_ID }}.dkr.ecr.{{ AWS_REGION }}.amazonaws.com/postgres:latest

- name: Deploy PostgreSQL in AWS EKS
  command: kubectl apply -f "{{ playbook_dir }}/roles/postgres_setup/files/postgres-deployment.yml"
  environment:
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    KUBECONFIG: "/home/ec2-user/.kube/config"
    PATH: "/usr/local/bin:/usr/bin:/bin"

- name: Deploy PostgreSQL Service in AWS EKS
  command: kubectl apply -f "~/workspace/springboot_sample_deployment/kubernetes/postgres-service.yml"
  environment:
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    KUBECONFIG: "/home/ec2-user/.kube/config"
    PATH: "/usr/local/bin:/usr/bin:/bin"
